import gradio as gr


def build_metadata_tab():
    """
    Builds the Metadata tab contents.

    Returns:
        dict: Gradio components keyed by name.
    """
    results = {}

    with gr.Column():
        gr.Markdown(
            "Upload an image generated by Nexfocus to inspect its embedded parameters and reapply them to the current session."
        )

        gr.HTML(
            '<nex-image-slot id="metadata_input_slot" '
            'data-bridge-id="metadata_input_image_bridge" '
            'data-upload-mode="api" '
            'data-preserve-metadata="true" '
            'data-path-field-id="metadata_input_image_path" '
            'data-workspace-field-id="metadata_input_workspace_id" '
            'data-label="For images created by Nexfocus" '
            'data-placeholder="Click or drop an image to inspect metadata"></nex-image-slot>'
        )

        results['metadata_input_image'] = gr.Image(
            label='Metadata Image',
            sources='upload',
            type='filepath',
            show_label=False,
            elem_id='metadata_input_image_bridge',
            elem_classes=['nex-image-slot-bridge']
        )

        results['metadata_input_image_path'] = gr.Textbox(
            label='Metadata Image',
            value='',
            visible=True,
            show_label=False,
            container=False,
            elem_id='metadata_input_image_path',
            elem_classes=['inpaint-hidden-mask-field']
        )

        results['metadata_input_workspace_id'] = gr.Textbox(
            label='Metadata Workspace',
            value='',
            visible=True,
            show_label=False,
            container=False,
            elem_id='metadata_input_workspace_id',
            elem_classes=['inpaint-hidden-mask-field']
        )

        results['metadata_import_button'] = gr.Button(
            value='Apply Metadata',
            variant='primary'
        )

        results['metadata_json'] = gr.Textbox(
            label='Metadata',
            lines=20,
            max_lines=40,
            interactive=False,
            show_copy_button=True
        )

    return results

